version: '3'
services:
  db:
    image: postgres:9.6-alpine

    networks:
      mynetwork:
        aliases:
          - db.exam.ext
    hostname: db
  app:
    depends_on:
      - db
#   volumes:
#     - ./logs:/usr/local/tomcat/logs
    ports:
      - 8009
      - 8080
    build: tomcat/.
    hostname: app
    networks:
      mynetwork:
        aliases:
          - app.exam.ext
  web:
    depends_on:
      - db
      - app
#   volumes:
#     - ./logs:/var/log/apache2
    ports:
      - "80:80"
      - "443:443"
    build: httpd/.
    hostname: web
    networks:
      mynetwork:
        aliases:
          - web.exam.ext


networks:
  mynetwork:
